FROM public.ecr.aws/ubuntu/ubuntu:18.04

# Build time parameters 
ARG SERVICE=sagemaker

RUN apt-get update && apt-get install -y curl \
    wget \
    git \
    python3.8 \
    python3-pip \
    python3.8-dev \
    vim \
    sudo \
    jq \
    unzip

# Install awscli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.6.3.zip" -o "awscliv2.zip" \
 && unzip -qq awscliv2.zip \
 && ./aws/install

# Add yq repository and install yq
RUN apt-get update && apt install -y software-properties-common \
 && sudo add-apt-repository ppa:rmescandon/yq \
 && apt update && apt install -y yq

# Install kubectl
RUN  curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl" \
 && chmod +x ./kubectl \
 && cp ./kubectl /bin

# Install eksctl
RUN curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp && mv /tmp/eksctl /bin

# Install Helm 
RUN curl -q -L "https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz" | tar zxf - -C /usr/local/bin/ \
 && mv /usr/local/bin/linux-amd64/helm /usr/local/bin/helm \
 && rm -r /usr/local/bin/linux-amd64 \
 && chmod +x /usr/local/bin/helm 

ENV SERVICE_REPO_PATH=/$SERVICE-controller
COPY ./test/e2e/requirements.txt requirements.txt

RUN ln -s /usr/bin/python3.8 /usr/bin/python \
 && python -m pip install --upgrade pip

RUN python -m pip install -r requirements.txt

WORKDIR /$SERVICE_REPO_PATH
CMD ["./test/canary/scripts/run_test.sh"]