apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: NotebookInstanceLifecycleConfig
metadata:
  name: test47
spec:
  notebookInstanceLifecycleConfigName: test47
  onStart:
    - content: cGlwIGluc3RhbGwgUElM
  # onCreate:
  #          - content: d2dldCBodHRwOi8vbWlycm9ycy5jdGFuLm9yZy9tYWNyb3MvbGF0ZXgvY29udHJpYi91cHF1b3RlLnppcA0KRU9G