apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: Model
metadata:
  name: <YOUR MODEL NAME>
spec:
  modelName: <YOUR MODEL NAME>
  primaryContainer:
    containerHostname: xgboost
    # The source of the model data
    modelDataURL: s3://<YOUR BUCKET>/sagemaker/xgboost/model/xgb-churn-prediction-model.tar.gz
    # The URL and tag of your ECR container  
    # If you are not on us-west-2 you can find an imageURI here https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-algo-docker-registry-paths.html
    image: 246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:0.90-2-cpu-py3
    environment:
      my_var: my_value
      my_var2: my_value2
  # Example arn:aws:iam::1234567890:role/service-role/AmazonSageMaker-ExecutionRole
  executionRoleARN: <YOUR SAGEMAKER ROLE ARN>