{{ if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ack-sagemaker-controller.app.fullname" . }}-leaderelection
{{ if .Values.leaderElection.namespace }}
  namespace: {{ .Values.leaderElection.namespace }}
{{ else }}
  namespace: {{ .Release.Namespace }}
{{ end }}
  labels:
    app.kubernetes.io/name: {{ include "ack-sagemaker-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-sagemaker-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-sagemaker-controller.chart.name-version" . }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch{{- end }}
