apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: TrainingJob
metadata:
  name: my-training-job
spec:
  trainingJobName: my-training-job # Name that will appear in SageMaker console
  hyperParameters: # Modify these parameters to meet your own script's needs
    max_depth: "5"
    gamma: "4"
    eta: "0.2"
    min_child_weight: "6"
    silent: "0"
    objective: "multi:softmax"
    num_class: "10"
    num_round: "10"
  algorithmSpecification:
    trainingImage: <YOUR ECR IMAGE> # The URL and tag of your ECR container
    # 433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1
    trainingInputMode: File
  roleARN: <YOUR SAGEMAKER ROLE ARN> # A role with SageMaker and S3 access
  # example arn:aws:iam::1234567890:role/service-role/AmazonSageMaker-ExecutionRole
  outputDataConfig:
    s3OutputPath: s3://<YOUR BUCKET>/output # The output path of our model
  resourceConfig:
    instanceCount: 1
    instanceType: ml.m4.xlarge
    volumeSizeInGB: 5
  stoppingCondition:
    maxRuntimeInSeconds: 86400
  inputDataConfig:
    - channelName: train
      dataSource:
        s3DataSource:
          s3DataType: S3Prefix
          s3URI: s3://<YOUR BUCKET>/sagemaker/training/train
          # source-data-bucket-718865417152-us-west-2
          s3DataDistributionType: FullyReplicated
      contentType: text/csv
      compressionType: None
    - channelName: validation
      dataSource:
        s3DataSource:
          s3DataType: S3Prefix
          s3URI: s3://<YOUR BUCKET>/sagemaker/training/validation
          # s3://source-data-bucket-718865417152-us-west-2
          s3DataDistributionType: FullyReplicated
      contentType: text/csv
      compressionType: None