---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-sagemaker-reader
  namespace: default
rules:
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - endpoints
  - endpointconfigs
  - hyperparametertuningjobs
  - models
  - processingjobs
  - trainingjobs
  - transformjobs
  verbs:
  - get
  - list
  - watch
