apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: ProcessingJob
metadata:
  name: my-processing-job
spec:
  processingJobName: my-processing-job # Name that will appear in SageMaker console
  roleARN: <YOUR SAGEMAKER ROLE ARN> # A role with SageMaker and S3 access
  # example arn:aws:iam::1234567890:role/service-role/AmazonSageMaker-ExecutionRole
  environment:
    my_var: my_value
    my_var2: my_value2
  appSpecification:
    imageURI: <YOUR ECR IMAGE> # The URL and tag of your ECR container   
    # 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.5.0-cpu-py36-ubuntu16.04 
    containerEntrypoint:
      - python
      - /opt/ml/processing/code/kmeans_preprocessing.py 
  processingResources:
    clusterConfig:
      instanceCount: 1
      instanceType: "ml.m5.large"
      volumeSizeInGB: 20
  processingInputs:
    - inputName: mnist_tar
      s3Input:
        s3URI: s3://<YOUR BUCKET>/algorithms/kmeans/mnist/mnist.pkl.gz # The source of our data
         # source-data-bucket-718865417152-us-west-2
        localPath: /opt/ml/processing/input
        s3DataType: S3Prefix
        s3InputMode: File
        s3CompressionType: None
    - inputName: source_code
      s3Input:
        s3URI: s3://<YOUR BUCKET>/sagemaker/processing/kmeans_preprocessing.py # The input path of our source code
        # source-data-bucket-718865417152-us-west-2
        localPath: /opt/ml/processing/code
        s3DataType: S3Prefix
        s3InputMode: File
        s3CompressionType: None
  processingOutputConfig:
    outputs:
      - outputName: train_data
        s3Output:
          s3URI: s3://<YOUR BUCKET>/sagemaker/processing/output/ # The output path of our training data
          localPath: /opt/ml/processing/output_train/
          s3UploadMode: EndOfJob
      - outputName: test_data
        s3Output:
          s3URI: s3://<YOUR BUCKET>/sagemaker/processing/output/  # The output path of our test data
          localPath: /opt/ml/processing/output_test/
          s3UploadMode: EndOfJob
      - outputName: valid_data
        s3Output:
          s3URI: s3://<YOUR BUCKET>/sagemaker/processing/output/  # The output path of our validation data
          localPath: /opt/ml/processing/output_valid/
          s3UploadMode: EndOfJob