apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: EndpointConfig
metadata:
  name: <YOUR ENDPOINT CONFIG NAME>
spec:
  endpointConfigName: <YOUR ENDPOINT CONFIG NAME>
  productionVariants:
  # Name of Model created in Sagemaker
  - modelName: <YOUR MODEL NAME> 
    variantName: AllTraffic
    instanceType: ml.c5.large
    initialVariantWeight: 1
    initialInstanceCount: 1
  # OPTIONAL To enable this endpoint to capture data from bias/quality/explainability dataCapture is required 
  dataCaptureConfig:
    enableCapture: true #
    destinationS3URI: s3://<YOUR BUCKET>/sagemaker/endpoint_config/datacapture
    initialSamplingPercentage: 100
    captureOptions:
    - captureMode: Input
    - captureMode: Output
    captureContentTypeHeader:
      csvContentTypes:
      - "text/csv"
      jsonContentTypes:
      - "application/json"