apiVersion: v1
kind: Service
metadata:
  name: ack-sagemaker-metrics-service
  namespace: ack-system
spec:
  selector:
    control-plane: controller
    name: ack-sagemaker-controller
  ports:
    - name: metricsport
      port: 8080
      targetPort: http
      protocol: TCP
  type: NodePort
