// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package data_quality_job_definition

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.DataQualityAppSpecification, b.ko.Spec.DataQualityAppSpecification) {
		delta.Add("Spec.DataQualityAppSpecification", a.ko.Spec.DataQualityAppSpecification, b.ko.Spec.DataQualityAppSpecification)
	} else if a.ko.Spec.DataQualityAppSpecification != nil && b.ko.Spec.DataQualityAppSpecification != nil {
		if len(a.ko.Spec.DataQualityAppSpecification.ContainerArguments) != len(b.ko.Spec.DataQualityAppSpecification.ContainerArguments) {
			delta.Add("Spec.DataQualityAppSpecification.ContainerArguments", a.ko.Spec.DataQualityAppSpecification.ContainerArguments, b.ko.Spec.DataQualityAppSpecification.ContainerArguments)
		} else if len(a.ko.Spec.DataQualityAppSpecification.ContainerArguments) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.DataQualityAppSpecification.ContainerArguments, b.ko.Spec.DataQualityAppSpecification.ContainerArguments) {
				delta.Add("Spec.DataQualityAppSpecification.ContainerArguments", a.ko.Spec.DataQualityAppSpecification.ContainerArguments, b.ko.Spec.DataQualityAppSpecification.ContainerArguments)
			}
		}
		if len(a.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint) != len(b.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint) {
			delta.Add("Spec.DataQualityAppSpecification.ContainerEntrypoint", a.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint, b.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint)
		} else if len(a.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint, b.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint) {
				delta.Add("Spec.DataQualityAppSpecification.ContainerEntrypoint", a.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint, b.ko.Spec.DataQualityAppSpecification.ContainerEntrypoint)
			}
		}
		if len(a.ko.Spec.DataQualityAppSpecification.Environment) != len(b.ko.Spec.DataQualityAppSpecification.Environment) {
			delta.Add("Spec.DataQualityAppSpecification.Environment", a.ko.Spec.DataQualityAppSpecification.Environment, b.ko.Spec.DataQualityAppSpecification.Environment)
		} else if len(a.ko.Spec.DataQualityAppSpecification.Environment) > 0 {
			if !ackcompare.MapStringStringPEqual(a.ko.Spec.DataQualityAppSpecification.Environment, b.ko.Spec.DataQualityAppSpecification.Environment) {
				delta.Add("Spec.DataQualityAppSpecification.Environment", a.ko.Spec.DataQualityAppSpecification.Environment, b.ko.Spec.DataQualityAppSpecification.Environment)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityAppSpecification.ImageURI, b.ko.Spec.DataQualityAppSpecification.ImageURI) {
			delta.Add("Spec.DataQualityAppSpecification.ImageURI", a.ko.Spec.DataQualityAppSpecification.ImageURI, b.ko.Spec.DataQualityAppSpecification.ImageURI)
		} else if a.ko.Spec.DataQualityAppSpecification.ImageURI != nil && b.ko.Spec.DataQualityAppSpecification.ImageURI != nil {
			if *a.ko.Spec.DataQualityAppSpecification.ImageURI != *b.ko.Spec.DataQualityAppSpecification.ImageURI {
				delta.Add("Spec.DataQualityAppSpecification.ImageURI", a.ko.Spec.DataQualityAppSpecification.ImageURI, b.ko.Spec.DataQualityAppSpecification.ImageURI)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI, b.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI) {
			delta.Add("Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI", a.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI, b.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI)
		} else if a.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI != nil && b.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI != nil {
			if *a.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI != *b.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI {
				delta.Add("Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI", a.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI, b.ko.Spec.DataQualityAppSpecification.PostAnalyticsProcessorSourceURI)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI, b.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI) {
			delta.Add("Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI", a.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI, b.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI)
		} else if a.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI != nil && b.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI != nil {
			if *a.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI != *b.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI {
				delta.Add("Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI", a.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI, b.ko.Spec.DataQualityAppSpecification.RecordPreprocessorSourceURI)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DataQualityBaselineConfig, b.ko.Spec.DataQualityBaselineConfig) {
		delta.Add("Spec.DataQualityBaselineConfig", a.ko.Spec.DataQualityBaselineConfig, b.ko.Spec.DataQualityBaselineConfig)
	} else if a.ko.Spec.DataQualityBaselineConfig != nil && b.ko.Spec.DataQualityBaselineConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityBaselineConfig.BaseliningJobName, b.ko.Spec.DataQualityBaselineConfig.BaseliningJobName) {
			delta.Add("Spec.DataQualityBaselineConfig.BaseliningJobName", a.ko.Spec.DataQualityBaselineConfig.BaseliningJobName, b.ko.Spec.DataQualityBaselineConfig.BaseliningJobName)
		} else if a.ko.Spec.DataQualityBaselineConfig.BaseliningJobName != nil && b.ko.Spec.DataQualityBaselineConfig.BaseliningJobName != nil {
			if *a.ko.Spec.DataQualityBaselineConfig.BaseliningJobName != *b.ko.Spec.DataQualityBaselineConfig.BaseliningJobName {
				delta.Add("Spec.DataQualityBaselineConfig.BaseliningJobName", a.ko.Spec.DataQualityBaselineConfig.BaseliningJobName, b.ko.Spec.DataQualityBaselineConfig.BaseliningJobName)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource, b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource) {
			delta.Add("Spec.DataQualityBaselineConfig.ConstraintsResource", a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource, b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource)
		} else if a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource != nil && b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI, b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI) {
				delta.Add("Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI", a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI, b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI)
			} else if a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI != nil && b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI != nil {
				if *a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI != *b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI {
					delta.Add("Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI", a.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI, b.ko.Spec.DataQualityBaselineConfig.ConstraintsResource.S3URI)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityBaselineConfig.StatisticsResource, b.ko.Spec.DataQualityBaselineConfig.StatisticsResource) {
			delta.Add("Spec.DataQualityBaselineConfig.StatisticsResource", a.ko.Spec.DataQualityBaselineConfig.StatisticsResource, b.ko.Spec.DataQualityBaselineConfig.StatisticsResource)
		} else if a.ko.Spec.DataQualityBaselineConfig.StatisticsResource != nil && b.ko.Spec.DataQualityBaselineConfig.StatisticsResource != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI, b.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI) {
				delta.Add("Spec.DataQualityBaselineConfig.StatisticsResource.S3URI", a.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI, b.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI)
			} else if a.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI != nil && b.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI != nil {
				if *a.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI != *b.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI {
					delta.Add("Spec.DataQualityBaselineConfig.StatisticsResource.S3URI", a.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI, b.ko.Spec.DataQualityBaselineConfig.StatisticsResource.S3URI)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput, b.ko.Spec.DataQualityJobInput) {
		delta.Add("Spec.DataQualityJobInput", a.ko.Spec.DataQualityJobInput, b.ko.Spec.DataQualityJobInput)
	} else if a.ko.Spec.DataQualityJobInput != nil && b.ko.Spec.DataQualityJobInput != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput, b.ko.Spec.DataQualityJobInput.EndpointInput) {
			delta.Add("Spec.DataQualityJobInput.EndpointInput", a.ko.Spec.DataQualityJobInput.EndpointInput, b.ko.Spec.DataQualityJobInput.EndpointInput)
		} else if a.ko.Spec.DataQualityJobInput.EndpointInput != nil && b.ko.Spec.DataQualityJobInput.EndpointInput != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset, b.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.EndTimeOffset", a.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset, b.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset != *b.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.EndTimeOffset", a.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset, b.ko.Spec.DataQualityJobInput.EndpointInput.EndTimeOffset)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName, b.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.EndpointName", a.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName, b.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName != *b.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.EndpointName", a.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName, b.ko.Spec.DataQualityJobInput.EndpointInput.EndpointName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute != *b.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.FeaturesAttribute)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.InferenceAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute != *b.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.InferenceAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.InferenceAttribute)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath, b.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.LocalPath", a.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath, b.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath != *b.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.LocalPath", a.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath, b.ko.Spec.DataQualityJobInput.EndpointInput.LocalPath)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute != *b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityAttribute)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute != *b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute", a.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute, b.ko.Spec.DataQualityJobInput.EndpointInput.ProbabilityThresholdAttribute)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType, b.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType", a.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType, b.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType != *b.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType", a.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType, b.ko.Spec.DataQualityJobInput.EndpointInput.S3DataDistributionType)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode, b.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.S3InputMode", a.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode, b.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode != *b.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.S3InputMode", a.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode, b.ko.Spec.DataQualityJobInput.EndpointInput.S3InputMode)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset, b.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset) {
				delta.Add("Spec.DataQualityJobInput.EndpointInput.StartTimeOffset", a.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset, b.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset)
			} else if a.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset != nil && b.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset != nil {
				if *a.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset != *b.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset {
					delta.Add("Spec.DataQualityJobInput.EndpointInput.StartTimeOffset", a.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset, b.ko.Spec.DataQualityJobInput.EndpointInput.StartTimeOffset)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobOutputConfig, b.ko.Spec.DataQualityJobOutputConfig) {
		delta.Add("Spec.DataQualityJobOutputConfig", a.ko.Spec.DataQualityJobOutputConfig, b.ko.Spec.DataQualityJobOutputConfig)
	} else if a.ko.Spec.DataQualityJobOutputConfig != nil && b.ko.Spec.DataQualityJobOutputConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.DataQualityJobOutputConfig.KMSKeyID, b.ko.Spec.DataQualityJobOutputConfig.KMSKeyID) {
			delta.Add("Spec.DataQualityJobOutputConfig.KMSKeyID", a.ko.Spec.DataQualityJobOutputConfig.KMSKeyID, b.ko.Spec.DataQualityJobOutputConfig.KMSKeyID)
		} else if a.ko.Spec.DataQualityJobOutputConfig.KMSKeyID != nil && b.ko.Spec.DataQualityJobOutputConfig.KMSKeyID != nil {
			if *a.ko.Spec.DataQualityJobOutputConfig.KMSKeyID != *b.ko.Spec.DataQualityJobOutputConfig.KMSKeyID {
				delta.Add("Spec.DataQualityJobOutputConfig.KMSKeyID", a.ko.Spec.DataQualityJobOutputConfig.KMSKeyID, b.ko.Spec.DataQualityJobOutputConfig.KMSKeyID)
			}
		}
		if len(a.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs) != len(b.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs) {
			delta.Add("Spec.DataQualityJobOutputConfig.MonitoringOutputs", a.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs, b.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs)
		} else if len(a.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs) > 0 {
			if !reflect.DeepEqual(a.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs, b.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs) {
				delta.Add("Spec.DataQualityJobOutputConfig.MonitoringOutputs", a.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs, b.ko.Spec.DataQualityJobOutputConfig.MonitoringOutputs)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.JobDefinitionName, b.ko.Spec.JobDefinitionName) {
		delta.Add("Spec.JobDefinitionName", a.ko.Spec.JobDefinitionName, b.ko.Spec.JobDefinitionName)
	} else if a.ko.Spec.JobDefinitionName != nil && b.ko.Spec.JobDefinitionName != nil {
		if *a.ko.Spec.JobDefinitionName != *b.ko.Spec.JobDefinitionName {
			delta.Add("Spec.JobDefinitionName", a.ko.Spec.JobDefinitionName, b.ko.Spec.JobDefinitionName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.JobResources, b.ko.Spec.JobResources) {
		delta.Add("Spec.JobResources", a.ko.Spec.JobResources, b.ko.Spec.JobResources)
	} else if a.ko.Spec.JobResources != nil && b.ko.Spec.JobResources != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.JobResources.ClusterConfig, b.ko.Spec.JobResources.ClusterConfig) {
			delta.Add("Spec.JobResources.ClusterConfig", a.ko.Spec.JobResources.ClusterConfig, b.ko.Spec.JobResources.ClusterConfig)
		} else if a.ko.Spec.JobResources.ClusterConfig != nil && b.ko.Spec.JobResources.ClusterConfig != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.JobResources.ClusterConfig.InstanceCount, b.ko.Spec.JobResources.ClusterConfig.InstanceCount) {
				delta.Add("Spec.JobResources.ClusterConfig.InstanceCount", a.ko.Spec.JobResources.ClusterConfig.InstanceCount, b.ko.Spec.JobResources.ClusterConfig.InstanceCount)
			} else if a.ko.Spec.JobResources.ClusterConfig.InstanceCount != nil && b.ko.Spec.JobResources.ClusterConfig.InstanceCount != nil {
				if *a.ko.Spec.JobResources.ClusterConfig.InstanceCount != *b.ko.Spec.JobResources.ClusterConfig.InstanceCount {
					delta.Add("Spec.JobResources.ClusterConfig.InstanceCount", a.ko.Spec.JobResources.ClusterConfig.InstanceCount, b.ko.Spec.JobResources.ClusterConfig.InstanceCount)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.JobResources.ClusterConfig.InstanceType, b.ko.Spec.JobResources.ClusterConfig.InstanceType) {
				delta.Add("Spec.JobResources.ClusterConfig.InstanceType", a.ko.Spec.JobResources.ClusterConfig.InstanceType, b.ko.Spec.JobResources.ClusterConfig.InstanceType)
			} else if a.ko.Spec.JobResources.ClusterConfig.InstanceType != nil && b.ko.Spec.JobResources.ClusterConfig.InstanceType != nil {
				if *a.ko.Spec.JobResources.ClusterConfig.InstanceType != *b.ko.Spec.JobResources.ClusterConfig.InstanceType {
					delta.Add("Spec.JobResources.ClusterConfig.InstanceType", a.ko.Spec.JobResources.ClusterConfig.InstanceType, b.ko.Spec.JobResources.ClusterConfig.InstanceType)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID, b.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID) {
				delta.Add("Spec.JobResources.ClusterConfig.VolumeKMSKeyID", a.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID, b.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID)
			} else if a.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID != nil && b.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID != nil {
				if *a.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID != *b.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID {
					delta.Add("Spec.JobResources.ClusterConfig.VolumeKMSKeyID", a.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID, b.ko.Spec.JobResources.ClusterConfig.VolumeKMSKeyID)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB, b.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB) {
				delta.Add("Spec.JobResources.ClusterConfig.VolumeSizeInGB", a.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB, b.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB)
			} else if a.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB != nil && b.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB != nil {
				if *a.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB != *b.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB {
					delta.Add("Spec.JobResources.ClusterConfig.VolumeSizeInGB", a.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB, b.ko.Spec.JobResources.ClusterConfig.VolumeSizeInGB)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfig, b.ko.Spec.NetworkConfig) {
		delta.Add("Spec.NetworkConfig", a.ko.Spec.NetworkConfig, b.ko.Spec.NetworkConfig)
	} else if a.ko.Spec.NetworkConfig != nil && b.ko.Spec.NetworkConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption, b.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption) {
			delta.Add("Spec.NetworkConfig.EnableInterContainerTrafficEncryption", a.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption, b.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption)
		} else if a.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption != nil && b.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption != nil {
			if *a.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption != *b.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption {
				delta.Add("Spec.NetworkConfig.EnableInterContainerTrafficEncryption", a.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption, b.ko.Spec.NetworkConfig.EnableInterContainerTrafficEncryption)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfig.EnableNetworkIsolation, b.ko.Spec.NetworkConfig.EnableNetworkIsolation) {
			delta.Add("Spec.NetworkConfig.EnableNetworkIsolation", a.ko.Spec.NetworkConfig.EnableNetworkIsolation, b.ko.Spec.NetworkConfig.EnableNetworkIsolation)
		} else if a.ko.Spec.NetworkConfig.EnableNetworkIsolation != nil && b.ko.Spec.NetworkConfig.EnableNetworkIsolation != nil {
			if *a.ko.Spec.NetworkConfig.EnableNetworkIsolation != *b.ko.Spec.NetworkConfig.EnableNetworkIsolation {
				delta.Add("Spec.NetworkConfig.EnableNetworkIsolation", a.ko.Spec.NetworkConfig.EnableNetworkIsolation, b.ko.Spec.NetworkConfig.EnableNetworkIsolation)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfig.VPCConfig, b.ko.Spec.NetworkConfig.VPCConfig) {
			delta.Add("Spec.NetworkConfig.VPCConfig", a.ko.Spec.NetworkConfig.VPCConfig, b.ko.Spec.NetworkConfig.VPCConfig)
		} else if a.ko.Spec.NetworkConfig.VPCConfig != nil && b.ko.Spec.NetworkConfig.VPCConfig != nil {
			if len(a.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs) != len(b.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs) {
				delta.Add("Spec.NetworkConfig.VPCConfig.SecurityGroupIDs", a.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs, b.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs)
			} else if len(a.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs, b.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs) {
					delta.Add("Spec.NetworkConfig.VPCConfig.SecurityGroupIDs", a.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs, b.ko.Spec.NetworkConfig.VPCConfig.SecurityGroupIDs)
				}
			}
			if len(a.ko.Spec.NetworkConfig.VPCConfig.Subnets) != len(b.ko.Spec.NetworkConfig.VPCConfig.Subnets) {
				delta.Add("Spec.NetworkConfig.VPCConfig.Subnets", a.ko.Spec.NetworkConfig.VPCConfig.Subnets, b.ko.Spec.NetworkConfig.VPCConfig.Subnets)
			} else if len(a.ko.Spec.NetworkConfig.VPCConfig.Subnets) > 0 {
				if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfig.VPCConfig.Subnets, b.ko.Spec.NetworkConfig.VPCConfig.Subnets) {
					delta.Add("Spec.NetworkConfig.VPCConfig.Subnets", a.ko.Spec.NetworkConfig.VPCConfig.Subnets, b.ko.Spec.NetworkConfig.VPCConfig.Subnets)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RoleARN, b.ko.Spec.RoleARN) {
		delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
	} else if a.ko.Spec.RoleARN != nil && b.ko.Spec.RoleARN != nil {
		if *a.ko.Spec.RoleARN != *b.ko.Spec.RoleARN {
			delta.Add("Spec.RoleARN", a.ko.Spec.RoleARN, b.ko.Spec.RoleARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StoppingCondition, b.ko.Spec.StoppingCondition) {
		delta.Add("Spec.StoppingCondition", a.ko.Spec.StoppingCondition, b.ko.Spec.StoppingCondition)
	} else if a.ko.Spec.StoppingCondition != nil && b.ko.Spec.StoppingCondition != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.StoppingCondition.MaxRuntimeInSeconds, b.ko.Spec.StoppingCondition.MaxRuntimeInSeconds) {
			delta.Add("Spec.StoppingCondition.MaxRuntimeInSeconds", a.ko.Spec.StoppingCondition.MaxRuntimeInSeconds, b.ko.Spec.StoppingCondition.MaxRuntimeInSeconds)
		} else if a.ko.Spec.StoppingCondition.MaxRuntimeInSeconds != nil && b.ko.Spec.StoppingCondition.MaxRuntimeInSeconds != nil {
			if *a.ko.Spec.StoppingCondition.MaxRuntimeInSeconds != *b.ko.Spec.StoppingCondition.MaxRuntimeInSeconds {
				delta.Add("Spec.StoppingCondition.MaxRuntimeInSeconds", a.ko.Spec.StoppingCondition.MaxRuntimeInSeconds, b.ko.Spec.StoppingCondition.MaxRuntimeInSeconds)
			}
		}
	}

	return delta
}
