// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DataQualityJobDefinitionSpec defines the desired state of DataQualityJobDefinition
type DataQualityJobDefinitionSpec struct {
	// +kubebuilder:validation:Required
	DataQualityAppSpecification *DataQualityAppSpecification `json:"dataQualityAppSpecification"`
	DataQualityBaselineConfig   *DataQualityBaselineConfig   `json:"dataQualityBaselineConfig,omitempty"`
	// +kubebuilder:validation:Required
	DataQualityJobInput *DataQualityJobInput `json:"dataQualityJobInput"`
	// +kubebuilder:validation:Required
	DataQualityJobOutputConfig *MonitoringOutputConfig `json:"dataQualityJobOutputConfig"`
	// +kubebuilder:validation:Required
	JobDefinitionName *string `json:"jobDefinitionName"`
	// +kubebuilder:validation:Required
	JobResources  *MonitoringResources     `json:"jobResources"`
	NetworkConfig *MonitoringNetworkConfig `json:"networkConfig,omitempty"`
	// +kubebuilder:validation:Required
	RoleARN           *string                      `json:"roleARN"`
	StoppingCondition *MonitoringStoppingCondition `json:"stoppingCondition,omitempty"`
	Tags              []*Tag                       `json:"tags,omitempty"`
}

// DataQualityJobDefinitionStatus defines the observed state of DataQualityJobDefinition
type DataQualityJobDefinitionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions       []*ackv1alpha1.Condition `json:"conditions"`
	JobDefinitionARN *string                  `json:"jobDefinitionARN,omitempty"`
}

// DataQualityJobDefinition is the Schema for the DataQualityJobDefinitions API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type DataQualityJobDefinition struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DataQualityJobDefinitionSpec   `json:"spec,omitempty"`
	Status            DataQualityJobDefinitionStatus `json:"status,omitempty"`
}

// DataQualityJobDefinitionList contains a list of DataQualityJobDefinition
// +kubebuilder:object:root=true
type DataQualityJobDefinitionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataQualityJobDefinition `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DataQualityJobDefinition{}, &DataQualityJobDefinitionList{})
}
