// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ModelExplainabilityJobDefinitionSpec defines the desired state of ModelExplainabilityJobDefinition.
type ModelExplainabilityJobDefinitionSpec struct {
	// The name of the model explainability job definition. The name must be unique
	// within an AWS Region in the AWS account.
	// +kubebuilder:validation:Required
	JobDefinitionName *string `json:"jobDefinitionName"`

	// +kubebuilder:validation:Required
	JobResources *MonitoringResources `json:"jobResources"`
	// Configures the model explainability job to run a specified Docker container
	// image.
	// +kubebuilder:validation:Required
	ModelExplainabilityAppSpecification *ModelExplainabilityAppSpecification `json:"modelExplainabilityAppSpecification"`
	// The baseline configuration for a model explainability job.
	ModelExplainabilityBaselineConfig *ModelExplainabilityBaselineConfig `json:"modelExplainabilityBaselineConfig,omitempty"`
	// Inputs for the model explainability job.
	// +kubebuilder:validation:Required
	ModelExplainabilityJobInput *ModelExplainabilityJobInput `json:"modelExplainabilityJobInput"`

	// +kubebuilder:validation:Required
	ModelExplainabilityJobOutputConfig *MonitoringOutputConfig `json:"modelExplainabilityJobOutputConfig"`
	// Networking options for a model explainability job.
	NetworkConfig *MonitoringNetworkConfig `json:"networkConfig,omitempty"`
	// The Amazon Resource Name (ARN) of an IAM role that Amazon SageMaker can assume
	// to perform tasks on your behalf.
	// +kubebuilder:validation:Required
	RoleARN *string `json:"roleARN"`

	StoppingCondition *MonitoringStoppingCondition `json:"stoppingCondition,omitempty"`
}

// ModelExplainabilityJobDefinitionStatus defines the observed state of ModelExplainabilityJobDefinition
type ModelExplainabilityJobDefinitionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// ModelExplainabilityJobDefinition is the Schema for the ModelExplainabilityJobDefinitions API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ModelExplainabilityJobDefinition struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ModelExplainabilityJobDefinitionSpec   `json:"spec,omitempty"`
	Status            ModelExplainabilityJobDefinitionStatus `json:"status,omitempty"`
}

// ModelExplainabilityJobDefinitionList contains a list of ModelExplainabilityJobDefinition
// +kubebuilder:object:root=true
type ModelExplainabilityJobDefinitionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ModelExplainabilityJobDefinition `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ModelExplainabilityJobDefinition{}, &ModelExplainabilityJobDefinitionList{})
}
