// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ModelPackageSpec defines the desired state of ModelPackage.
//
// A versioned model that can be deployed for SageMaker inference.
type ModelPackageSpec struct {
	// An array of additional Inference Specification objects. Each additional Inference
	// Specification specifies artifacts based on this model package that can be
	// used on inference endpoints. Generally used with SageMaker Neo to store the
	// compiled artifacts.
	AdditionalInferenceSpecifications []*AdditionalInferenceSpecificationDefinition `json:"additionalInferenceSpecifications,omitempty"`
	// A description for the approval status of the model.
	ApprovalDescription *string `json:"approvalDescription,omitempty"`
	// Whether to certify the model package for listing on Amazon Web Services Marketplace.
	//
	// This parameter is optional for unversioned models, and does not apply to
	// versioned models.
	CertifyForMarketplace *bool `json:"certifyForMarketplace,omitempty"`
	// A unique token that guarantees that the call to this API is idempotent.
	ClientToken *string `json:"clientToken,omitempty"`
	// The metadata properties associated with the model package versions.
	CustomerMetadataProperties map[string]*string `json:"customerMetadataProperties,omitempty"`
	// The machine learning domain of your model package and its components. Common
	// machine learning domains include computer vision and natural language processing.
	Domain *string `json:"domain,omitempty"`
	// Represents the drift check baselines that can be used when the model monitor
	// is set using the model package. For more information, see the topic on Drift
	// Detection against Previous Baselines in SageMaker Pipelines (https://docs.aws.amazon.com/sagemaker/latest/dg/pipelines-quality-clarify-baseline-lifecycle.html#pipelines-quality-clarify-baseline-drift-detection)
	// in the Amazon SageMaker Developer Guide.
	DriftCheckBaselines *DriftCheckBaselines `json:"driftCheckBaselines,omitempty"`
	// Specifies details about inference jobs that can be run with models based
	// on this model package, including the following:
	//
	//    * The Amazon ECR paths of containers that contain the inference code and
	//    model artifacts.
	//
	//    * The instance types that the model package supports for transform jobs
	//    and real-time endpoints used for inference.
	//
	//    * The input and output content formats that the model package supports
	//    for inference.
	InferenceSpecification *InferenceSpecification `json:"inferenceSpecification,omitempty"`

	MetadataProperties *MetadataProperties `json:"metadataProperties,omitempty"`
	// Whether the model is approved for deployment.
	//
	// This parameter is optional for versioned models, and does not apply to unversioned
	// models.
	//
	// For versioned models, the value of this parameter must be set to Approved
	// to deploy the model.
	ModelApprovalStatus *string `json:"modelApprovalStatus,omitempty"`
	// A structure that contains model metrics reports.
	ModelMetrics *ModelMetrics `json:"modelMetrics,omitempty"`
	// A description of the model package.
	ModelPackageDescription *string `json:"modelPackageDescription,omitempty"`
	// The name or Amazon Resource Name (ARN) of the model package group that this
	// model version belongs to.
	//
	// This parameter is required for versioned models, and does not apply to unversioned
	// models.
	ModelPackageGroupName *string `json:"modelPackageGroupName,omitempty"`
	// The name of the model package. The name must have 1 to 63 characters. Valid
	// characters are a-z, A-Z, 0-9, and - (hyphen).
	//
	// This parameter is required for unversioned models. It is not applicable to
	// versioned models.
	ModelPackageName *string `json:"modelPackageName,omitempty"`
	// The Amazon Simple Storage Service (Amazon S3) path where the sample payload
	// are stored. This path must point to a single gzip compressed tar archive
	// (.tar.gz suffix).
	SamplePayloadURL *string `json:"samplePayloadURL,omitempty"`
	// Details about the algorithm that was used to create the model package.
	SourceAlgorithmSpecification *SourceAlgorithmSpecification `json:"sourceAlgorithmSpecification,omitempty"`
	// A list of key value pairs associated with the model. For more information,
	// see Tagging Amazon Web Services resources (https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html)
	// in the Amazon Web Services General Reference Guide.
	Tags []*Tag `json:"tags,omitempty"`
	// The machine learning task your model package accomplishes. Common machine
	// learning tasks include object detection and image classification. The following
	// tasks are supported by Inference Recommender: "IMAGE_CLASSIFICATION" | "OBJECT_DETECTION"
	// | "TEXT_GENERATION" |"IMAGE_SEGMENTATION" | "FILL_MASK" | "CLASSIFICATION"
	// | "REGRESSION" | "OTHER".
	//
	// Specify "OTHER" if none of the tasks listed fit your use case.
	Task *string `json:"task,omitempty"`
	// Specifies configurations for one or more transform jobs that SageMaker runs
	// to test the model package.
	ValidationSpecification *ModelPackageValidationSpecification `json:"validationSpecification,omitempty"`
}

// ModelPackageStatus defines the observed state of ModelPackage
type ModelPackageStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// A timestamp specifying when the model package was created.
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	// The last time that the model package was modified.
	// +kubebuilder:validation:Optional
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	// The current status of the model package.
	// +kubebuilder:validation:Optional
	ModelPackageStatus *string `json:"modelPackageStatus,omitempty"`
	// Details about the current status of the model package.
	// +kubebuilder:validation:Optional
	ModelPackageStatusDetails *ModelPackageStatusDetails `json:"modelPackageStatusDetails,omitempty"`
}

// ModelPackage is the Schema for the ModelPackages API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="STATUS",type=string,priority=0,JSONPath=`.status.modelPackageStatus`
type ModelPackage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ModelPackageSpec   `json:"spec,omitempty"`
	Status            ModelPackageStatus `json:"status,omitempty"`
}

// ModelPackageList contains a list of ModelPackage
// +kubebuilder:object:root=true
type ModelPackageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ModelPackage `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ModelPackage{}, &ModelPackageList{})
}
